version: '3'
networks:
  default:
    external:
      name: cc_bridge
services: 
  ruoyi-vue:
    image: {{DOCKER_IMAGE}}
    container_name: ruoyi-vue
    restart: unless-stopped
    networks:
      - default
    environment:
      SERVER_PORT: 8090
      SPRING_PROFILES_ACTIVE: prod
      JVM_OPTS: "-Xms2048M -Xmx2048m -Xmn512m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m"
    ports:
      - "8090:8090"
      - "8899:8899"
    volumes:
      - ./logs:/home/app/logs
      - ./uploadPath:/home/app/uploadPath
      - ./wwwroot_release:/home/app/wwwroot_release